import Head from 'next/head'
import Link from 'next/link'
import { Container } from '../components/sharedstyles'
import { getSortedPostsData } from '../lib/posts'
import styled from 'styled-components'
import { CardPostWrapper, TitleCardPost } from '../components/card'
import Date from '../components/date'

const Heading1 = styled.h1`
  margin-bottom: 2rem;
  font-size: 2rem;
  text-align: left;
  font-weight: 700;
`
const Tag = styled.a`
display: flex;
border: 1px solid black;
width: fit-content;
border-radius: 15px;
padding: 5px;
font-size: 10px;
line-height: 5px;

&:hover {
  background-color: lime;  
}
`

export default function Home({ allPostsData }) {
  console.log(allPostsData, 'allPostsData')
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading1>Blog</Heading1>
      <div>
        {allPostsData.map(({ id, date, title, tag }) => (
          <CardPostWrapper key={id}>
            <Link href={`/posts/${id}`}>
              <TitleCardPost>{title}</TitleCardPost>
            </Link>
            <Link href={`/tag/${tag}`}>
              <Tag key={tag}>#{tag}</Tag>
            </Link>
            <Date dateString={date} />
          </CardPostWrapper>
        ))}
      </div>
    </Container>
  )
}

export async function getStaticProps() {
  const allPostsData = getSortedPostsData()
  console.log(allPostsData, 'allPostsData')

  return {
    props: {
      allPostsData
    }
  }
}

