import Head from 'next/head'
import Link from 'next/link'
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
} from '../components/sharedstyles'
import { getSortedPostsData } from '../lib/posts'
import Date from '../components/date'

export default function Home({ allPostsData }) {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h2>Blog</h2>
      </div>
      <div>
        {allPostsData.map(({ id, date, title }) => (
          <>
            <Link href={`/posts/${id}`}>
              <a>{title}</a>
            </Link>
            <Date dateString={date} />
          </>
        ))}
      </div>
    </Container>
  )
}

export async function getStaticProps() {
  const allPostsData = getSortedPostsData()
  return {
    props: {
      allPostsData
    }
  }
}
